package io.token;

import com.google.protobuf.ByteString;
import io.token.rpc.client.RpcChannelFactory;
import io.token.security.SecretKey;

import java.util.List;

import static java.lang.String.format;

/**
 * Main entry point to the Token SDK. Use {@link io.token.TokenIO.Builder}
 * class to create an instance of the {@link TokenIOAsync} or {@link TokenIO}.
 *
 * <p>
 * The class provides synchronous API with {@link TokenIOAsync} providing an
 * asynchronous version. {@link TokenIOAsync} instance can be obtained by
 * calling {@link #async} method.
 * </p>
 */
public final class TokenIO {
    /**
     * Used to create a new {@link TokenIO} instances.
     */
    public static final class Builder {
        private String hostName;
        private int port;

        /**
         * Sets the host name of the Token Gateway Service to connect to.
         *
         * @param hostName host name, e.g. 'api.token.io'
         * @return this builder instance
         */
        public Builder hostName(String hostName) {
            this.hostName = hostName;
            return this;
        }

        /**
         * Sets the port of the Token Gateway Service to connect to.
         *
         * @param port port number
         * @return this builder instance
         */
        public Builder port(int port) {
            this.port = port;
            return this;
        }

        /**
         * Builds and returns a new {@link TokenIO} instance.
         *
         * @return {@link TokenIO} instance
         */
        public TokenIO build() {
            return buildAsync().sync();
        }

        /**
         * Builds and returns a new {@link TokenIOAsync} instance.
         *
         * @return {@link TokenIO} instance
         */
        public TokenIOAsync buildAsync() {
            return new TokenIOAsync(RpcChannelFactory.forTarget(format("dns:///%s:%d/", hostName, port)));
        }
    }

    /**
     * Creates a new {@link Builder} instance that is used to configure and
     * build a {@link TokenIO} instance.
     *
     * @return builder
     */
    public static Builder builder() {
        return new Builder();
    }

    private final TokenIOAsync async;

    /**
     * @param async real implementation that the calls are delegated to
     */
    TokenIO(TokenIOAsync async) {
        this.async = async;
    }

    /**
     * @return asynchronous version of the account API
     */
    public TokenIOAsync async() {
        return async;
    }

    /**
     * Creates a new Token member with a pair of auto generated keys and the
     * given alias.
     *
     * @param alias member alias to use, must be unique
     * @return newly created member
     */
    public Member createMember(String alias) {
        return async.createMember(alias)
                .map(MemberAsync::sync)
                .toBlocking()
                .single();
    }

    /**
     * Logs in an existing member to the system.
     *
     * @param memberId member id
     * @param key secret/public key pair to use
     * @return logged in member
     */
    public Member login(String memberId, SecretKey key) {
        return async.login(memberId, key)
                .map(MemberAsync::sync)
                .toBlocking()
                .single();
    }

    /**
     * Logs in an existing member to the system, using the alias
     *
     * @param alias member id
     * @param key secret/public key pair to use
     * @return logged in member
     */
    public Member loginWithAlias(String alias, SecretKey key) {
        return async.loginWithAlias(alias, key)
                .map(MemberAsync::sync)
                .toBlocking()
                .single();
    }

    /**
     * Notifies to link accounts
     *
     * @param alias alias to notify
     * @param bankId bank to link
     * @param accountLinkPayload payload generated by bank
     */
    public void notifyLinkAccounts(String alias, String bankId, byte[] accountLinkPayload) {
        async.notifyLinkAccounts(alias, bankId, accountLinkPayload)
                .map(empty -> null)
                .toBlocking()
                .single();
    }

    /**
     * Notifies to add a key
     *
     * @param alias alias to notify
     * @param publicKey public key to add
     * @param tags tags for the public key
     * @return nothing
     */
    public void notifyAddKey(String alias, byte[] publicKey, List<String> tags) {
        async.notifyAddKey(alias, publicKey, tags)
                .map(empty -> null)
                .toBlocking()
                .single();
    }
    /**
     * Notifies to link accounts and add a key
     *
     * @param alias alias to notify
     * @param bankId bankId to link
     * @param accountLinkPayload payload generated by bank
     * @param publicKey public key to add
     * @param tags tags for the public key
     * @return nothing
     */
    public void notifyLinkAccountsAndAddKey(String alias, String bankId, byte[] accountLinkPayload,
                                            byte[] publicKey, List<String> tags) {
        async.notifyLinkAccountsAndAddKey(alias, bankId, accountLinkPayload, publicKey, tags)
                .map(empty -> null)
                .toBlocking()
                .single();
    }
}
